### ISSUE TITLE
Request: Please add the dark theme

### ISSUE THREAD

**Issue by ErikThiart** [hjgarcia1/phpstorm-brackets#1]
Man, I love PHPstorm but they have a shit editor. 

Please, will you make the Brackets Dark Theme for PHPstorm. 

I will buy some beer if you visit South Africa.

**Comment by fz-sl** [comment]
can you make php storm scheme like Dark Brackets Editor ?  if you can ... It would be Awesome ;))))

**Comment by activate-engineering** [comment]
Sure i can make one. I will add it soon.

**Comment by activate-engineering** [comment]
Made a new repo with a bigger collection of themes

https://github.com/hjgarcia1/phpstorm-themes

Will be updating that one regularly.
